### PR TITLE
UI fixed for "Confirmation Card", Typo fixed

### PR DESCRIPTION
**Pull request by amaan-ahmad**
Hey @Charlie85270,

I have fixed a UI mistake in Confirmation Card, there were Primary colors on both buttons, which is incorrect from a UI perspective. Also fixed a typo mistake in "Modale with footer actions"

- Before 
image

- After
image

### CODE REVIEW

**Comment by Charlie85270** [comment]
Hi amaan-ahmad  ! 

Thanks for your PR ! 
it seems that there are conflicts, we will be able to merge when they are resolved

Charlie

**Comment by tomasvn** [comment]
@amaan-ahmad IMO the delete button should have a color of red, which indicates warning, instead of the blue color

**Comment by Charlie85270** [comment]
Hi guys, 
I'm not a designer so my opinion may not be the right one, but I would also have put the delete button in red, no ?

**Comment by amaan-ahmad** [comment]
@tomasvn @Charlie85270 guys I am understanding your perspective about the button color, 
but it is about being the "Primary color" for action buttons, not specifically "red" or "indigo". 

It is all about the hierarchy, below I am quoting a paragraph from ["Refactoring UI" by Adam Wathan, Steve Schoger](https://www.goodreads.com/en/book/show/43190966-refactoring-ui)

> • Primary actions should be obvious. Solid, high contrast background
colors work great here.
• Secondary actions should be clear but not prominent. Outline styles or
lower contrast background colors are great options.
• Tertiary actions should be discoverable but unobtrusive. Styling these
actions like links is usually the best approach

image

I would recommend reading [Refactoring UI](https://www.goodreads.com/en/book/show/43190966-refactoring-ui) to become better at design. 🎨

Regards,
Amaan Ahmad

**Comment by amaan-ahmad** [comment]
@Charlie85270 I think something went wrong while I was resolving conflicts.

**Comment by Charlie85270** [comment]
Thanks amaan-ahmad  for the resource, I understand the initial problem ;) 
For the primary color to use, it's a story of taste and color, both are valid.
Regarding the build, there is an unclosed div on the components : 
image

You can reproduce with `yarn build` command

**Comment by amaan-ahmad** [comment]
Thanks @Charlie85270 now all checks are passed and the build is successful. Now it can be merged and PR can be closed then.

**Comment by tomasvn** [comment]
yes but, the delete indicates, something that cannot be returned, so imo the color combination is not correct

**Pull request merged**
